version: '3.9'

services:  
  donor_db:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: donor_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - "./donor-db.sql:/docker-entrypoint-initdb.d/1.sql"
    container_name: donor_db
